name: Trigger auto deployment for ornacloudbackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ornacloudbackend-AutoDeployTrigger-4b0c20c6-b952-4e70-8e2d-f34fbaad8db4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ORNACLOUDBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORNACLOUDBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORNACLOUDBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.ORNACLOUDBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORNACLOUDBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ornacloudbackend
          resourceGroup: ornacloud-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


